"""empty message

Revision ID: 26a6f459f5d7
Revises: 9a75b52f4045
Create Date: 2021-05-03 22:34:15.273038

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '26a6f459f5d7'
down_revision = '9a75b52f4045'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_option', sa.Column('input_option', sa.JSON(), nullable=True))
    op.drop_column('product_option', 'input_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_option', sa.Column('input_type', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('product_option', 'input_option')
    # ### end Alembic commands ###
