"""empty message

Revision ID: 2eca5f35346c
Revises: 73478de07715
Create Date: 2021-05-02 20:03:29.058816

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2eca5f35346c'
down_revision = '73478de07715'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_option', 'option')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_option', sa.Column('option', mysql.JSON(), nullable=True))
    # ### end Alembic commands ###
