"""empty message

Revision ID: 704172c04273
Revises: 337f074b1fd6
Create Date: 2021-05-02 21:38:06.674223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '704172c04273'
down_revision = '337f074b1fd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('home_category', sa.Column('is_published', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('home_category', 'is_published')
    # ### end Alembic commands ###
