"""empty message

Revision ID: 835f00f0bfbe
Revises: 704172c04273
Create Date: 2021-05-03 22:02:42.109297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '835f00f0bfbe'
down_revision = '704172c04273'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('thumbnail', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'thumbnail')
    # ### end Alembic commands ###
