"""empty message

Revision ID: 868388f53cfe
Revises: 1ad42a07f7a1
Create Date: 2021-05-02 16:25:39.651435

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '868388f53cfe'
down_revision = '1ad42a07f7a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('category', sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('category', 'updatedAt')
    op.drop_column('category', 'createdAt')
    op.add_column('product', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('product', sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('product', 'updatedAt')
    op.drop_column('product', 'createdAt')
    op.add_column('product_option', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('product_option', sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('product_option', 'updatedAt')
    op.drop_column('product_option', 'createdAt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_option', sa.Column('createdAt', mysql.DATETIME(), nullable=True))
    op.add_column('product_option', sa.Column('updatedAt', mysql.DATETIME(), nullable=True))
    op.drop_column('product_option', 'updated_on')
    op.drop_column('product_option', 'created_on')
    op.add_column('product', sa.Column('createdAt', mysql.DATETIME(), nullable=True))
    op.add_column('product', sa.Column('updatedAt', mysql.DATETIME(), nullable=True))
    op.drop_column('product', 'updated_on')
    op.drop_column('product', 'created_on')
    op.add_column('category', sa.Column('createdAt', mysql.DATETIME(), nullable=True))
    op.add_column('category', sa.Column('updatedAt', mysql.DATETIME(), nullable=True))
    op.drop_column('category', 'updated_on')
    op.drop_column('category', 'created_on')
    # ### end Alembic commands ###
